
name: Debug Build for PR

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 11
        cache: 'gradle'
    - name: Download dependencies
      run: ./gradlew androidDependencies
    - name: Build debug
      run: ./gradlew bundleDebug
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: 'Download artifact'
      uses: actions/download-artifact@v2
      with:
        name: apk
        path: ${{ runner.temp }}
